LOCAL_PATH:= $(call my-dir)

# PROTOBUF
PROTOBUF_PATH := $(LOCAL_PATH)
include $(CLEAR_VARS)
LOCAL_MODULE := protobuf
LOCAL_SRC_FILES := $(PROTOBUF_PATH)/lib/$(TARGET_ARCH_ABI)/libprotobuf.a
LOCAL_EXPORT_C_INCLUDES := $(PROTOBUF_PATH)/include
include $(PREBUILT_STATIC_LIBRARY)

