// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AudioFocusRequestMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AudioFocusRequestMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AudioFocusRequestMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "AudioFocusTypeEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AudioFocusRequestMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AudioFocusRequestMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AudioFocusRequestMessage_2eproto;
namespace aasdk {
namespace proto {
namespace messages {
class AudioFocusRequest;
struct AudioFocusRequestDefaultTypeInternal;
extern AudioFocusRequestDefaultTypeInternal _AudioFocusRequest_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
PROTOBUF_NAMESPACE_OPEN
template<> ::aasdk::proto::messages::AudioFocusRequest* Arena::CreateMaybeMessage<::aasdk::proto::messages::AudioFocusRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aasdk {
namespace proto {
namespace messages {

// ===================================================================

class AudioFocusRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aasdk.proto.messages.AudioFocusRequest) */ {
 public:
  inline AudioFocusRequest() : AudioFocusRequest(nullptr) {}
  ~AudioFocusRequest() override;
  explicit constexpr AudioFocusRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudioFocusRequest(const AudioFocusRequest& from);
  AudioFocusRequest(AudioFocusRequest&& from) noexcept
    : AudioFocusRequest() {
    *this = ::std::move(from);
  }

  inline AudioFocusRequest& operator=(const AudioFocusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioFocusRequest& operator=(AudioFocusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioFocusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioFocusRequest* internal_default_instance() {
    return reinterpret_cast<const AudioFocusRequest*>(
               &_AudioFocusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AudioFocusRequest& a, AudioFocusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AudioFocusRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioFocusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AudioFocusRequest* New() const final {
    return new AudioFocusRequest();
  }

  AudioFocusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AudioFocusRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AudioFocusRequest& from);
  void MergeFrom(const AudioFocusRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioFocusRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aasdk.proto.messages.AudioFocusRequest";
  }
  protected:
  explicit AudioFocusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAudioFocusTypeFieldNumber = 1,
  };
  // required .aasdk.proto.enums.AudioFocusType.Enum audio_focus_type = 1;
  bool has_audio_focus_type() const;
  private:
  bool _internal_has_audio_focus_type() const;
  public:
  void clear_audio_focus_type();
  ::aasdk::proto::enums::AudioFocusType_Enum audio_focus_type() const;
  void set_audio_focus_type(::aasdk::proto::enums::AudioFocusType_Enum value);
  private:
  ::aasdk::proto::enums::AudioFocusType_Enum _internal_audio_focus_type() const;
  void _internal_set_audio_focus_type(::aasdk::proto::enums::AudioFocusType_Enum value);
  public:

  // @@protoc_insertion_point(class_scope:aasdk.proto.messages.AudioFocusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int audio_focus_type_;
  friend struct ::TableStruct_AudioFocusRequestMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AudioFocusRequest

// required .aasdk.proto.enums.AudioFocusType.Enum audio_focus_type = 1;
inline bool AudioFocusRequest::_internal_has_audio_focus_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AudioFocusRequest::has_audio_focus_type() const {
  return _internal_has_audio_focus_type();
}
inline void AudioFocusRequest::clear_audio_focus_type() {
  audio_focus_type_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::aasdk::proto::enums::AudioFocusType_Enum AudioFocusRequest::_internal_audio_focus_type() const {
  return static_cast< ::aasdk::proto::enums::AudioFocusType_Enum >(audio_focus_type_);
}
inline ::aasdk::proto::enums::AudioFocusType_Enum AudioFocusRequest::audio_focus_type() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.AudioFocusRequest.audio_focus_type)
  return _internal_audio_focus_type();
}
inline void AudioFocusRequest::_internal_set_audio_focus_type(::aasdk::proto::enums::AudioFocusType_Enum value) {
  assert(::aasdk::proto::enums::AudioFocusType_Enum_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  audio_focus_type_ = value;
}
inline void AudioFocusRequest::set_audio_focus_type(::aasdk::proto::enums::AudioFocusType_Enum value) {
  _internal_set_audio_focus_type(value);
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.AudioFocusRequest.audio_focus_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace proto
}  // namespace aasdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AudioFocusRequestMessage_2eproto
