// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BluetoothChannelMessageIdsEnum.proto

#include "BluetoothChannelMessageIdsEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace aasdk {
namespace proto {
namespace ids {
constexpr BluetoothChannelMessage::BluetoothChannelMessage(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct BluetoothChannelMessageDefaultTypeInternal {
  constexpr BluetoothChannelMessageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~BluetoothChannelMessageDefaultTypeInternal() {}
  union {
    BluetoothChannelMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT BluetoothChannelMessageDefaultTypeInternal _BluetoothChannelMessage_default_instance_;
}  // namespace ids
}  // namespace proto
}  // namespace aasdk
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_BluetoothChannelMessageIdsEnum_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_BluetoothChannelMessageIdsEnum_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_BluetoothChannelMessageIdsEnum_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aasdk::proto::ids::BluetoothChannelMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::aasdk::proto::ids::BluetoothChannelMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::aasdk::proto::ids::_BluetoothChannelMessage_default_instance_),
};

const char descriptor_table_protodef_BluetoothChannelMessageIdsEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n$BluetoothChannelMessageIdsEnum.proto\022\017"
  "aasdk.proto.ids\"k\n\027BluetoothChannelMessa"
  "ge\"P\n\004Enum\022\010\n\004NONE\020\000\022\025\n\017PAIRING_REQUEST\020"
  "\201\200\002\022\026\n\020PAIRING_RESPONSE\020\202\200\002\022\017\n\tAUTH_DATA"
  "\020\203\200\002"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BluetoothChannelMessageIdsEnum_2eproto = {
  false, false, 164, descriptor_table_protodef_BluetoothChannelMessageIdsEnum_2eproto, "BluetoothChannelMessageIdsEnum.proto", 
  &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_BluetoothChannelMessageIdsEnum_2eproto::offsets,
  file_level_metadata_BluetoothChannelMessageIdsEnum_2eproto, file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto, file_level_service_descriptors_BluetoothChannelMessageIdsEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_getter() {
  return &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_BluetoothChannelMessageIdsEnum_2eproto(&descriptor_table_BluetoothChannelMessageIdsEnum_2eproto);
namespace aasdk {
namespace proto {
namespace ids {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BluetoothChannelMessage_Enum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_BluetoothChannelMessageIdsEnum_2eproto);
  return file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto[0];
}
bool BluetoothChannelMessage_Enum_IsValid(int value) {
  switch (value) {
    case 0:
    case 32769:
    case 32770:
    case 32771:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::NONE;
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::PAIRING_REQUEST;
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::PAIRING_RESPONSE;
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::AUTH_DATA;
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::Enum_MIN;
constexpr BluetoothChannelMessage_Enum BluetoothChannelMessage::Enum_MAX;
constexpr int BluetoothChannelMessage::Enum_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class BluetoothChannelMessage::_Internal {
 public:
};

BluetoothChannelMessage::BluetoothChannelMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.ids.BluetoothChannelMessage)
}
BluetoothChannelMessage::BluetoothChannelMessage(const BluetoothChannelMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:aasdk.proto.ids.BluetoothChannelMessage)
}

void BluetoothChannelMessage::SharedCtor() {
}

BluetoothChannelMessage::~BluetoothChannelMessage() {
  // @@protoc_insertion_point(destructor:aasdk.proto.ids.BluetoothChannelMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void BluetoothChannelMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BluetoothChannelMessage::ArenaDtor(void* object) {
  BluetoothChannelMessage* _this = reinterpret_cast< BluetoothChannelMessage* >(object);
  (void)_this;
}
void BluetoothChannelMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void BluetoothChannelMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BluetoothChannelMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.ids.BluetoothChannelMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BluetoothChannelMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BluetoothChannelMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.ids.BluetoothChannelMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.ids.BluetoothChannelMessage)
  return target;
}

size_t BluetoothChannelMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aasdk.proto.ids.BluetoothChannelMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BluetoothChannelMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:aasdk.proto.ids.BluetoothChannelMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const BluetoothChannelMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BluetoothChannelMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:aasdk.proto.ids.BluetoothChannelMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:aasdk.proto.ids.BluetoothChannelMessage)
    MergeFrom(*source);
  }
}

void BluetoothChannelMessage::MergeFrom(const BluetoothChannelMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.ids.BluetoothChannelMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void BluetoothChannelMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:aasdk.proto.ids.BluetoothChannelMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BluetoothChannelMessage::CopyFrom(const BluetoothChannelMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.ids.BluetoothChannelMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BluetoothChannelMessage::IsInitialized() const {
  return true;
}

void BluetoothChannelMessage::InternalSwap(BluetoothChannelMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BluetoothChannelMessage::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_getter, &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_once,
      file_level_metadata_BluetoothChannelMessageIdsEnum_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ids
}  // namespace proto
}  // namespace aasdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::aasdk::proto::ids::BluetoothChannelMessage* Arena::CreateMaybeMessage< ::aasdk::proto::ids::BluetoothChannelMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aasdk::proto::ids::BluetoothChannelMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
