// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BluetoothPairingResponseMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BluetoothPairingResponseMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BluetoothPairingResponseMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BluetoothPairingStatusEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BluetoothPairingResponseMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BluetoothPairingResponseMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BluetoothPairingResponseMessage_2eproto;
namespace aasdk {
namespace proto {
namespace messages {
class BluetoothPairingResponse;
struct BluetoothPairingResponseDefaultTypeInternal;
extern BluetoothPairingResponseDefaultTypeInternal _BluetoothPairingResponse_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
PROTOBUF_NAMESPACE_OPEN
template<> ::aasdk::proto::messages::BluetoothPairingResponse* Arena::CreateMaybeMessage<::aasdk::proto::messages::BluetoothPairingResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aasdk {
namespace proto {
namespace messages {

// ===================================================================

class BluetoothPairingResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aasdk.proto.messages.BluetoothPairingResponse) */ {
 public:
  inline BluetoothPairingResponse() : BluetoothPairingResponse(nullptr) {}
  ~BluetoothPairingResponse() override;
  explicit constexpr BluetoothPairingResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BluetoothPairingResponse(const BluetoothPairingResponse& from);
  BluetoothPairingResponse(BluetoothPairingResponse&& from) noexcept
    : BluetoothPairingResponse() {
    *this = ::std::move(from);
  }

  inline BluetoothPairingResponse& operator=(const BluetoothPairingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BluetoothPairingResponse& operator=(BluetoothPairingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BluetoothPairingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BluetoothPairingResponse* internal_default_instance() {
    return reinterpret_cast<const BluetoothPairingResponse*>(
               &_BluetoothPairingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BluetoothPairingResponse& a, BluetoothPairingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BluetoothPairingResponse* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BluetoothPairingResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BluetoothPairingResponse* New() const final {
    return new BluetoothPairingResponse();
  }

  BluetoothPairingResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BluetoothPairingResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BluetoothPairingResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BluetoothPairingResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BluetoothPairingResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aasdk.proto.messages.BluetoothPairingResponse";
  }
  protected:
  explicit BluetoothPairingResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAlreadyPairedFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // required bool already_paired = 1;
  bool has_already_paired() const;
  private:
  bool _internal_has_already_paired() const;
  public:
  void clear_already_paired();
  bool already_paired() const;
  void set_already_paired(bool value);
  private:
  bool _internal_already_paired() const;
  void _internal_set_already_paired(bool value);
  public:

  // required .aasdk.proto.enums.BluetoothPairingStatus.Enum status = 2;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::aasdk::proto::enums::BluetoothPairingStatus_Enum status() const;
  void set_status(::aasdk::proto::enums::BluetoothPairingStatus_Enum value);
  private:
  ::aasdk::proto::enums::BluetoothPairingStatus_Enum _internal_status() const;
  void _internal_set_status(::aasdk::proto::enums::BluetoothPairingStatus_Enum value);
  public:

  // @@protoc_insertion_point(class_scope:aasdk.proto.messages.BluetoothPairingResponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool already_paired_;
  int status_;
  friend struct ::TableStruct_BluetoothPairingResponseMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BluetoothPairingResponse

// required bool already_paired = 1;
inline bool BluetoothPairingResponse::_internal_has_already_paired() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BluetoothPairingResponse::has_already_paired() const {
  return _internal_has_already_paired();
}
inline void BluetoothPairingResponse::clear_already_paired() {
  already_paired_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool BluetoothPairingResponse::_internal_already_paired() const {
  return already_paired_;
}
inline bool BluetoothPairingResponse::already_paired() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.BluetoothPairingResponse.already_paired)
  return _internal_already_paired();
}
inline void BluetoothPairingResponse::_internal_set_already_paired(bool value) {
  _has_bits_[0] |= 0x00000001u;
  already_paired_ = value;
}
inline void BluetoothPairingResponse::set_already_paired(bool value) {
  _internal_set_already_paired(value);
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.BluetoothPairingResponse.already_paired)
}

// required .aasdk.proto.enums.BluetoothPairingStatus.Enum status = 2;
inline bool BluetoothPairingResponse::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BluetoothPairingResponse::has_status() const {
  return _internal_has_status();
}
inline void BluetoothPairingResponse::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::aasdk::proto::enums::BluetoothPairingStatus_Enum BluetoothPairingResponse::_internal_status() const {
  return static_cast< ::aasdk::proto::enums::BluetoothPairingStatus_Enum >(status_);
}
inline ::aasdk::proto::enums::BluetoothPairingStatus_Enum BluetoothPairingResponse::status() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.BluetoothPairingResponse.status)
  return _internal_status();
}
inline void BluetoothPairingResponse::_internal_set_status(::aasdk::proto::enums::BluetoothPairingStatus_Enum value) {
  assert(::aasdk::proto::enums::BluetoothPairingStatus_Enum_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  status_ = value;
}
inline void BluetoothPairingResponse::set_status(::aasdk::proto::enums::BluetoothPairingStatus_Enum value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.BluetoothPairingResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace proto
}  // namespace aasdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BluetoothPairingResponseMessage_2eproto
