// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InputEventIndicationMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_InputEventIndicationMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_InputEventIndicationMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "TouchEventData.pb.h"
#include "ButtonEventsData.pb.h"
#include "AbsoluteInputEventsData.pb.h"
#include "RelativeInputEventsData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_InputEventIndicationMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_InputEventIndicationMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_InputEventIndicationMessage_2eproto;
namespace aasdk {
namespace proto {
namespace messages {
class InputEventIndication;
struct InputEventIndicationDefaultTypeInternal;
extern InputEventIndicationDefaultTypeInternal _InputEventIndication_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
PROTOBUF_NAMESPACE_OPEN
template<> ::aasdk::proto::messages::InputEventIndication* Arena::CreateMaybeMessage<::aasdk::proto::messages::InputEventIndication>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aasdk {
namespace proto {
namespace messages {

// ===================================================================

class InputEventIndication final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aasdk.proto.messages.InputEventIndication) */ {
 public:
  inline InputEventIndication() : InputEventIndication(nullptr) {}
  ~InputEventIndication() override;
  explicit constexpr InputEventIndication(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InputEventIndication(const InputEventIndication& from);
  InputEventIndication(InputEventIndication&& from) noexcept
    : InputEventIndication() {
    *this = ::std::move(from);
  }

  inline InputEventIndication& operator=(const InputEventIndication& from) {
    CopyFrom(from);
    return *this;
  }
  inline InputEventIndication& operator=(InputEventIndication&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InputEventIndication& default_instance() {
    return *internal_default_instance();
  }
  static inline const InputEventIndication* internal_default_instance() {
    return reinterpret_cast<const InputEventIndication*>(
               &_InputEventIndication_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InputEventIndication& a, InputEventIndication& b) {
    a.Swap(&b);
  }
  inline void Swap(InputEventIndication* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InputEventIndication* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InputEventIndication* New() const final {
    return new InputEventIndication();
  }

  InputEventIndication* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InputEventIndication>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InputEventIndication& from);
  void MergeFrom(const InputEventIndication& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputEventIndication* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aasdk.proto.messages.InputEventIndication";
  }
  protected:
  explicit InputEventIndication(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTouchEventFieldNumber = 3,
    kButtonEventFieldNumber = 4,
    kAbsoluteInputEventFieldNumber = 5,
    kRelativeInputEventFieldNumber = 6,
    kTimestampFieldNumber = 1,
    kDispChannelFieldNumber = 2,
  };
  // optional .aasdk.proto.data.TouchEvent touch_event = 3;
  bool has_touch_event() const;
  private:
  bool _internal_has_touch_event() const;
  public:
  void clear_touch_event();
  const ::aasdk::proto::data::TouchEvent& touch_event() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::aasdk::proto::data::TouchEvent* release_touch_event();
  ::aasdk::proto::data::TouchEvent* mutable_touch_event();
  void set_allocated_touch_event(::aasdk::proto::data::TouchEvent* touch_event);
  private:
  const ::aasdk::proto::data::TouchEvent& _internal_touch_event() const;
  ::aasdk::proto::data::TouchEvent* _internal_mutable_touch_event();
  public:
  void unsafe_arena_set_allocated_touch_event(
      ::aasdk::proto::data::TouchEvent* touch_event);
  ::aasdk::proto::data::TouchEvent* unsafe_arena_release_touch_event();

  // optional .aasdk.proto.data.ButtonEvents button_event = 4;
  bool has_button_event() const;
  private:
  bool _internal_has_button_event() const;
  public:
  void clear_button_event();
  const ::aasdk::proto::data::ButtonEvents& button_event() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::aasdk::proto::data::ButtonEvents* release_button_event();
  ::aasdk::proto::data::ButtonEvents* mutable_button_event();
  void set_allocated_button_event(::aasdk::proto::data::ButtonEvents* button_event);
  private:
  const ::aasdk::proto::data::ButtonEvents& _internal_button_event() const;
  ::aasdk::proto::data::ButtonEvents* _internal_mutable_button_event();
  public:
  void unsafe_arena_set_allocated_button_event(
      ::aasdk::proto::data::ButtonEvents* button_event);
  ::aasdk::proto::data::ButtonEvents* unsafe_arena_release_button_event();

  // optional .aasdk.proto.data.AbsoluteInputEvents absolute_input_event = 5;
  bool has_absolute_input_event() const;
  private:
  bool _internal_has_absolute_input_event() const;
  public:
  void clear_absolute_input_event();
  const ::aasdk::proto::data::AbsoluteInputEvents& absolute_input_event() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::aasdk::proto::data::AbsoluteInputEvents* release_absolute_input_event();
  ::aasdk::proto::data::AbsoluteInputEvents* mutable_absolute_input_event();
  void set_allocated_absolute_input_event(::aasdk::proto::data::AbsoluteInputEvents* absolute_input_event);
  private:
  const ::aasdk::proto::data::AbsoluteInputEvents& _internal_absolute_input_event() const;
  ::aasdk::proto::data::AbsoluteInputEvents* _internal_mutable_absolute_input_event();
  public:
  void unsafe_arena_set_allocated_absolute_input_event(
      ::aasdk::proto::data::AbsoluteInputEvents* absolute_input_event);
  ::aasdk::proto::data::AbsoluteInputEvents* unsafe_arena_release_absolute_input_event();

  // optional .aasdk.proto.data.RelativeInputEvents relative_input_event = 6;
  bool has_relative_input_event() const;
  private:
  bool _internal_has_relative_input_event() const;
  public:
  void clear_relative_input_event();
  const ::aasdk::proto::data::RelativeInputEvents& relative_input_event() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::aasdk::proto::data::RelativeInputEvents* release_relative_input_event();
  ::aasdk::proto::data::RelativeInputEvents* mutable_relative_input_event();
  void set_allocated_relative_input_event(::aasdk::proto::data::RelativeInputEvents* relative_input_event);
  private:
  const ::aasdk::proto::data::RelativeInputEvents& _internal_relative_input_event() const;
  ::aasdk::proto::data::RelativeInputEvents* _internal_mutable_relative_input_event();
  public:
  void unsafe_arena_set_allocated_relative_input_event(
      ::aasdk::proto::data::RelativeInputEvents* relative_input_event);
  ::aasdk::proto::data::RelativeInputEvents* unsafe_arena_release_relative_input_event();

  // required uint64 timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional int32 disp_channel = 2;
  bool has_disp_channel() const;
  private:
  bool _internal_has_disp_channel() const;
  public:
  void clear_disp_channel();
  ::PROTOBUF_NAMESPACE_ID::int32 disp_channel() const;
  void set_disp_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_disp_channel() const;
  void _internal_set_disp_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:aasdk.proto.messages.InputEventIndication)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::aasdk::proto::data::TouchEvent* touch_event_;
  ::aasdk::proto::data::ButtonEvents* button_event_;
  ::aasdk::proto::data::AbsoluteInputEvents* absolute_input_event_;
  ::aasdk::proto::data::RelativeInputEvents* relative_input_event_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 disp_channel_;
  friend struct ::TableStruct_InputEventIndicationMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InputEventIndication

// required uint64 timestamp = 1;
inline bool InputEventIndication::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool InputEventIndication::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void InputEventIndication::clear_timestamp() {
  timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 InputEventIndication::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 InputEventIndication::timestamp() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.timestamp)
  return _internal_timestamp();
}
inline void InputEventIndication::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  timestamp_ = value;
}
inline void InputEventIndication::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.InputEventIndication.timestamp)
}

// optional int32 disp_channel = 2;
inline bool InputEventIndication::_internal_has_disp_channel() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool InputEventIndication::has_disp_channel() const {
  return _internal_has_disp_channel();
}
inline void InputEventIndication::clear_disp_channel() {
  disp_channel_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 InputEventIndication::_internal_disp_channel() const {
  return disp_channel_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 InputEventIndication::disp_channel() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.disp_channel)
  return _internal_disp_channel();
}
inline void InputEventIndication::_internal_set_disp_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  disp_channel_ = value;
}
inline void InputEventIndication::set_disp_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_disp_channel(value);
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.InputEventIndication.disp_channel)
}

// optional .aasdk.proto.data.TouchEvent touch_event = 3;
inline bool InputEventIndication::_internal_has_touch_event() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || touch_event_ != nullptr);
  return value;
}
inline bool InputEventIndication::has_touch_event() const {
  return _internal_has_touch_event();
}
inline const ::aasdk::proto::data::TouchEvent& InputEventIndication::_internal_touch_event() const {
  const ::aasdk::proto::data::TouchEvent* p = touch_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::TouchEvent&>(
      ::aasdk::proto::data::_TouchEvent_default_instance_);
}
inline const ::aasdk::proto::data::TouchEvent& InputEventIndication::touch_event() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.touch_event)
  return _internal_touch_event();
}
inline void InputEventIndication::unsafe_arena_set_allocated_touch_event(
    ::aasdk::proto::data::TouchEvent* touch_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(touch_event_);
  }
  touch_event_ = touch_event;
  if (touch_event) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.messages.InputEventIndication.touch_event)
}
inline ::aasdk::proto::data::TouchEvent* InputEventIndication::release_touch_event() {
  _has_bits_[0] &= ~0x00000001u;
  ::aasdk::proto::data::TouchEvent* temp = touch_event_;
  touch_event_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::aasdk::proto::data::TouchEvent* InputEventIndication::unsafe_arena_release_touch_event() {
  // @@protoc_insertion_point(field_release:aasdk.proto.messages.InputEventIndication.touch_event)
  _has_bits_[0] &= ~0x00000001u;
  ::aasdk::proto::data::TouchEvent* temp = touch_event_;
  touch_event_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::TouchEvent* InputEventIndication::_internal_mutable_touch_event() {
  _has_bits_[0] |= 0x00000001u;
  if (touch_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::aasdk::proto::data::TouchEvent>(GetArenaForAllocation());
    touch_event_ = p;
  }
  return touch_event_;
}
inline ::aasdk::proto::data::TouchEvent* InputEventIndication::mutable_touch_event() {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.InputEventIndication.touch_event)
  return _internal_mutable_touch_event();
}
inline void InputEventIndication::set_allocated_touch_event(::aasdk::proto::data::TouchEvent* touch_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(touch_event_);
  }
  if (touch_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(touch_event));
    if (message_arena != submessage_arena) {
      touch_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, touch_event, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  touch_event_ = touch_event;
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.messages.InputEventIndication.touch_event)
}

// optional .aasdk.proto.data.ButtonEvents button_event = 4;
inline bool InputEventIndication::_internal_has_button_event() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || button_event_ != nullptr);
  return value;
}
inline bool InputEventIndication::has_button_event() const {
  return _internal_has_button_event();
}
inline const ::aasdk::proto::data::ButtonEvents& InputEventIndication::_internal_button_event() const {
  const ::aasdk::proto::data::ButtonEvents* p = button_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::ButtonEvents&>(
      ::aasdk::proto::data::_ButtonEvents_default_instance_);
}
inline const ::aasdk::proto::data::ButtonEvents& InputEventIndication::button_event() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.button_event)
  return _internal_button_event();
}
inline void InputEventIndication::unsafe_arena_set_allocated_button_event(
    ::aasdk::proto::data::ButtonEvents* button_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(button_event_);
  }
  button_event_ = button_event;
  if (button_event) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.messages.InputEventIndication.button_event)
}
inline ::aasdk::proto::data::ButtonEvents* InputEventIndication::release_button_event() {
  _has_bits_[0] &= ~0x00000002u;
  ::aasdk::proto::data::ButtonEvents* temp = button_event_;
  button_event_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::aasdk::proto::data::ButtonEvents* InputEventIndication::unsafe_arena_release_button_event() {
  // @@protoc_insertion_point(field_release:aasdk.proto.messages.InputEventIndication.button_event)
  _has_bits_[0] &= ~0x00000002u;
  ::aasdk::proto::data::ButtonEvents* temp = button_event_;
  button_event_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::ButtonEvents* InputEventIndication::_internal_mutable_button_event() {
  _has_bits_[0] |= 0x00000002u;
  if (button_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::aasdk::proto::data::ButtonEvents>(GetArenaForAllocation());
    button_event_ = p;
  }
  return button_event_;
}
inline ::aasdk::proto::data::ButtonEvents* InputEventIndication::mutable_button_event() {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.InputEventIndication.button_event)
  return _internal_mutable_button_event();
}
inline void InputEventIndication::set_allocated_button_event(::aasdk::proto::data::ButtonEvents* button_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(button_event_);
  }
  if (button_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(button_event));
    if (message_arena != submessage_arena) {
      button_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, button_event, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  button_event_ = button_event;
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.messages.InputEventIndication.button_event)
}

// optional .aasdk.proto.data.AbsoluteInputEvents absolute_input_event = 5;
inline bool InputEventIndication::_internal_has_absolute_input_event() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || absolute_input_event_ != nullptr);
  return value;
}
inline bool InputEventIndication::has_absolute_input_event() const {
  return _internal_has_absolute_input_event();
}
inline const ::aasdk::proto::data::AbsoluteInputEvents& InputEventIndication::_internal_absolute_input_event() const {
  const ::aasdk::proto::data::AbsoluteInputEvents* p = absolute_input_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::AbsoluteInputEvents&>(
      ::aasdk::proto::data::_AbsoluteInputEvents_default_instance_);
}
inline const ::aasdk::proto::data::AbsoluteInputEvents& InputEventIndication::absolute_input_event() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.absolute_input_event)
  return _internal_absolute_input_event();
}
inline void InputEventIndication::unsafe_arena_set_allocated_absolute_input_event(
    ::aasdk::proto::data::AbsoluteInputEvents* absolute_input_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(absolute_input_event_);
  }
  absolute_input_event_ = absolute_input_event;
  if (absolute_input_event) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.messages.InputEventIndication.absolute_input_event)
}
inline ::aasdk::proto::data::AbsoluteInputEvents* InputEventIndication::release_absolute_input_event() {
  _has_bits_[0] &= ~0x00000004u;
  ::aasdk::proto::data::AbsoluteInputEvents* temp = absolute_input_event_;
  absolute_input_event_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::aasdk::proto::data::AbsoluteInputEvents* InputEventIndication::unsafe_arena_release_absolute_input_event() {
  // @@protoc_insertion_point(field_release:aasdk.proto.messages.InputEventIndication.absolute_input_event)
  _has_bits_[0] &= ~0x00000004u;
  ::aasdk::proto::data::AbsoluteInputEvents* temp = absolute_input_event_;
  absolute_input_event_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::AbsoluteInputEvents* InputEventIndication::_internal_mutable_absolute_input_event() {
  _has_bits_[0] |= 0x00000004u;
  if (absolute_input_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::aasdk::proto::data::AbsoluteInputEvents>(GetArenaForAllocation());
    absolute_input_event_ = p;
  }
  return absolute_input_event_;
}
inline ::aasdk::proto::data::AbsoluteInputEvents* InputEventIndication::mutable_absolute_input_event() {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.InputEventIndication.absolute_input_event)
  return _internal_mutable_absolute_input_event();
}
inline void InputEventIndication::set_allocated_absolute_input_event(::aasdk::proto::data::AbsoluteInputEvents* absolute_input_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(absolute_input_event_);
  }
  if (absolute_input_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(absolute_input_event));
    if (message_arena != submessage_arena) {
      absolute_input_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, absolute_input_event, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  absolute_input_event_ = absolute_input_event;
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.messages.InputEventIndication.absolute_input_event)
}

// optional .aasdk.proto.data.RelativeInputEvents relative_input_event = 6;
inline bool InputEventIndication::_internal_has_relative_input_event() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || relative_input_event_ != nullptr);
  return value;
}
inline bool InputEventIndication::has_relative_input_event() const {
  return _internal_has_relative_input_event();
}
inline const ::aasdk::proto::data::RelativeInputEvents& InputEventIndication::_internal_relative_input_event() const {
  const ::aasdk::proto::data::RelativeInputEvents* p = relative_input_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::RelativeInputEvents&>(
      ::aasdk::proto::data::_RelativeInputEvents_default_instance_);
}
inline const ::aasdk::proto::data::RelativeInputEvents& InputEventIndication::relative_input_event() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.InputEventIndication.relative_input_event)
  return _internal_relative_input_event();
}
inline void InputEventIndication::unsafe_arena_set_allocated_relative_input_event(
    ::aasdk::proto::data::RelativeInputEvents* relative_input_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(relative_input_event_);
  }
  relative_input_event_ = relative_input_event;
  if (relative_input_event) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.messages.InputEventIndication.relative_input_event)
}
inline ::aasdk::proto::data::RelativeInputEvents* InputEventIndication::release_relative_input_event() {
  _has_bits_[0] &= ~0x00000008u;
  ::aasdk::proto::data::RelativeInputEvents* temp = relative_input_event_;
  relative_input_event_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::aasdk::proto::data::RelativeInputEvents* InputEventIndication::unsafe_arena_release_relative_input_event() {
  // @@protoc_insertion_point(field_release:aasdk.proto.messages.InputEventIndication.relative_input_event)
  _has_bits_[0] &= ~0x00000008u;
  ::aasdk::proto::data::RelativeInputEvents* temp = relative_input_event_;
  relative_input_event_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::RelativeInputEvents* InputEventIndication::_internal_mutable_relative_input_event() {
  _has_bits_[0] |= 0x00000008u;
  if (relative_input_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::aasdk::proto::data::RelativeInputEvents>(GetArenaForAllocation());
    relative_input_event_ = p;
  }
  return relative_input_event_;
}
inline ::aasdk::proto::data::RelativeInputEvents* InputEventIndication::mutable_relative_input_event() {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.InputEventIndication.relative_input_event)
  return _internal_mutable_relative_input_event();
}
inline void InputEventIndication::set_allocated_relative_input_event(::aasdk::proto::data::RelativeInputEvents* relative_input_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(relative_input_event_);
  }
  if (relative_input_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(relative_input_event));
    if (message_arena != submessage_arena) {
      relative_input_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, relative_input_event, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  relative_input_event_ = relative_input_event;
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.messages.InputEventIndication.relative_input_event)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace proto
}  // namespace aasdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_InputEventIndicationMessage_2eproto
