// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorEventIndicationMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SensorEventIndicationMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SensorEventIndicationMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "GPSLocationData.pb.h"
#include "CompassData.pb.h"
#include "SpeedData.pb.h"
#include "RPMData.pb.h"
#include "OdometerData.pb.h"
#include "FuelLevelData.pb.h"
#include "ParkingBrakeData.pb.h"
#include "GearData.pb.h"
#include "DiagnosticsData.pb.h"
#include "NightModeData.pb.h"
#include "EnvironmentData.pb.h"
#include "HVACData.pb.h"
#include "DrivingStatusData.pb.h"
#include "SteeringWheelData.pb.h"
#include "PassengerData.pb.h"
#include "DoorData.pb.h"
#include "LightData.pb.h"
#include "AccelData.pb.h"
#include "GyroData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SensorEventIndicationMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SensorEventIndicationMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SensorEventIndicationMessage_2eproto;
namespace aasdk {
namespace proto {
namespace messages {
class SensorEventIndication;
struct SensorEventIndicationDefaultTypeInternal;
extern SensorEventIndicationDefaultTypeInternal _SensorEventIndication_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
PROTOBUF_NAMESPACE_OPEN
template<> ::aasdk::proto::messages::SensorEventIndication* Arena::CreateMaybeMessage<::aasdk::proto::messages::SensorEventIndication>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aasdk {
namespace proto {
namespace messages {

// ===================================================================

class SensorEventIndication final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aasdk.proto.messages.SensorEventIndication) */ {
 public:
  inline SensorEventIndication() : SensorEventIndication(nullptr) {}
  ~SensorEventIndication() override;
  explicit constexpr SensorEventIndication(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SensorEventIndication(const SensorEventIndication& from);
  SensorEventIndication(SensorEventIndication&& from) noexcept
    : SensorEventIndication() {
    *this = ::std::move(from);
  }

  inline SensorEventIndication& operator=(const SensorEventIndication& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorEventIndication& operator=(SensorEventIndication&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensorEventIndication& default_instance() {
    return *internal_default_instance();
  }
  static inline const SensorEventIndication* internal_default_instance() {
    return reinterpret_cast<const SensorEventIndication*>(
               &_SensorEventIndication_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SensorEventIndication& a, SensorEventIndication& b) {
    a.Swap(&b);
  }
  inline void Swap(SensorEventIndication* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorEventIndication* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SensorEventIndication* New() const final {
    return new SensorEventIndication();
  }

  SensorEventIndication* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SensorEventIndication>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SensorEventIndication& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SensorEventIndication& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorEventIndication* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aasdk.proto.messages.SensorEventIndication";
  }
  protected:
  explicit SensorEventIndication(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGpsLocationFieldNumber = 1,
    kCompassFieldNumber = 2,
    kSpeedFieldNumber = 3,
    kRpmFieldNumber = 4,
    kOdometerFieldNumber = 5,
    kFuelLevelFieldNumber = 6,
    kParkingBrakeFieldNumber = 7,
    kGearFieldNumber = 8,
    kDiagnosticsFieldNumber = 9,
    kNightModeFieldNumber = 10,
    kEnviormentFieldNumber = 11,
    kHvacFieldNumber = 12,
    kDrivingStatusFieldNumber = 13,
    kSteeringWheelFieldNumber = 14,
    kPassengerFieldNumber = 15,
    kDoorFieldNumber = 16,
    kLightFieldNumber = 17,
    kAccelFieldNumber = 19,
    kGyroFieldNumber = 20,
  };
  // repeated .aasdk.proto.data.GPSLocation gps_location = 1;
  int gps_location_size() const;
  private:
  int _internal_gps_location_size() const;
  public:
  void clear_gps_location();
  ::aasdk::proto::data::GPSLocation* mutable_gps_location(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::GPSLocation >*
      mutable_gps_location();
  private:
  const ::aasdk::proto::data::GPSLocation& _internal_gps_location(int index) const;
  ::aasdk::proto::data::GPSLocation* _internal_add_gps_location();
  public:
  const ::aasdk::proto::data::GPSLocation& gps_location(int index) const;
  ::aasdk::proto::data::GPSLocation* add_gps_location();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::GPSLocation >&
      gps_location() const;

  // repeated .aasdk.proto.data.Compass compass = 2;
  int compass_size() const;
  private:
  int _internal_compass_size() const;
  public:
  void clear_compass();
  ::aasdk::proto::data::Compass* mutable_compass(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Compass >*
      mutable_compass();
  private:
  const ::aasdk::proto::data::Compass& _internal_compass(int index) const;
  ::aasdk::proto::data::Compass* _internal_add_compass();
  public:
  const ::aasdk::proto::data::Compass& compass(int index) const;
  ::aasdk::proto::data::Compass* add_compass();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Compass >&
      compass() const;

  // repeated .aasdk.proto.data.Speed speed = 3;
  int speed_size() const;
  private:
  int _internal_speed_size() const;
  public:
  void clear_speed();
  ::aasdk::proto::data::Speed* mutable_speed(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Speed >*
      mutable_speed();
  private:
  const ::aasdk::proto::data::Speed& _internal_speed(int index) const;
  ::aasdk::proto::data::Speed* _internal_add_speed();
  public:
  const ::aasdk::proto::data::Speed& speed(int index) const;
  ::aasdk::proto::data::Speed* add_speed();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Speed >&
      speed() const;

  // repeated .aasdk.proto.data.RPM rpm = 4;
  int rpm_size() const;
  private:
  int _internal_rpm_size() const;
  public:
  void clear_rpm();
  ::aasdk::proto::data::RPM* mutable_rpm(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::RPM >*
      mutable_rpm();
  private:
  const ::aasdk::proto::data::RPM& _internal_rpm(int index) const;
  ::aasdk::proto::data::RPM* _internal_add_rpm();
  public:
  const ::aasdk::proto::data::RPM& rpm(int index) const;
  ::aasdk::proto::data::RPM* add_rpm();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::RPM >&
      rpm() const;

  // repeated .aasdk.proto.data.Odometer odometer = 5;
  int odometer_size() const;
  private:
  int _internal_odometer_size() const;
  public:
  void clear_odometer();
  ::aasdk::proto::data::Odometer* mutable_odometer(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Odometer >*
      mutable_odometer();
  private:
  const ::aasdk::proto::data::Odometer& _internal_odometer(int index) const;
  ::aasdk::proto::data::Odometer* _internal_add_odometer();
  public:
  const ::aasdk::proto::data::Odometer& odometer(int index) const;
  ::aasdk::proto::data::Odometer* add_odometer();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Odometer >&
      odometer() const;

  // repeated .aasdk.proto.data.FuelLevel fuel_level = 6;
  int fuel_level_size() const;
  private:
  int _internal_fuel_level_size() const;
  public:
  void clear_fuel_level();
  ::aasdk::proto::data::FuelLevel* mutable_fuel_level(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::FuelLevel >*
      mutable_fuel_level();
  private:
  const ::aasdk::proto::data::FuelLevel& _internal_fuel_level(int index) const;
  ::aasdk::proto::data::FuelLevel* _internal_add_fuel_level();
  public:
  const ::aasdk::proto::data::FuelLevel& fuel_level(int index) const;
  ::aasdk::proto::data::FuelLevel* add_fuel_level();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::FuelLevel >&
      fuel_level() const;

  // repeated .aasdk.proto.data.ParkingBrake parking_brake = 7;
  int parking_brake_size() const;
  private:
  int _internal_parking_brake_size() const;
  public:
  void clear_parking_brake();
  ::aasdk::proto::data::ParkingBrake* mutable_parking_brake(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::ParkingBrake >*
      mutable_parking_brake();
  private:
  const ::aasdk::proto::data::ParkingBrake& _internal_parking_brake(int index) const;
  ::aasdk::proto::data::ParkingBrake* _internal_add_parking_brake();
  public:
  const ::aasdk::proto::data::ParkingBrake& parking_brake(int index) const;
  ::aasdk::proto::data::ParkingBrake* add_parking_brake();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::ParkingBrake >&
      parking_brake() const;

  // repeated .aasdk.proto.data.Gear gear = 8;
  int gear_size() const;
  private:
  int _internal_gear_size() const;
  public:
  void clear_gear();
  ::aasdk::proto::data::Gear* mutable_gear(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gear >*
      mutable_gear();
  private:
  const ::aasdk::proto::data::Gear& _internal_gear(int index) const;
  ::aasdk::proto::data::Gear* _internal_add_gear();
  public:
  const ::aasdk::proto::data::Gear& gear(int index) const;
  ::aasdk::proto::data::Gear* add_gear();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gear >&
      gear() const;

  // repeated .aasdk.proto.data.Diagnostics diagnostics = 9;
  int diagnostics_size() const;
  private:
  int _internal_diagnostics_size() const;
  public:
  void clear_diagnostics();
  ::aasdk::proto::data::Diagnostics* mutable_diagnostics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Diagnostics >*
      mutable_diagnostics();
  private:
  const ::aasdk::proto::data::Diagnostics& _internal_diagnostics(int index) const;
  ::aasdk::proto::data::Diagnostics* _internal_add_diagnostics();
  public:
  const ::aasdk::proto::data::Diagnostics& diagnostics(int index) const;
  ::aasdk::proto::data::Diagnostics* add_diagnostics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Diagnostics >&
      diagnostics() const;

  // repeated .aasdk.proto.data.NightMode night_mode = 10;
  int night_mode_size() const;
  private:
  int _internal_night_mode_size() const;
  public:
  void clear_night_mode();
  ::aasdk::proto::data::NightMode* mutable_night_mode(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::NightMode >*
      mutable_night_mode();
  private:
  const ::aasdk::proto::data::NightMode& _internal_night_mode(int index) const;
  ::aasdk::proto::data::NightMode* _internal_add_night_mode();
  public:
  const ::aasdk::proto::data::NightMode& night_mode(int index) const;
  ::aasdk::proto::data::NightMode* add_night_mode();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::NightMode >&
      night_mode() const;

  // repeated .aasdk.proto.data.Environment enviorment = 11;
  int enviorment_size() const;
  private:
  int _internal_enviorment_size() const;
  public:
  void clear_enviorment();
  ::aasdk::proto::data::Environment* mutable_enviorment(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Environment >*
      mutable_enviorment();
  private:
  const ::aasdk::proto::data::Environment& _internal_enviorment(int index) const;
  ::aasdk::proto::data::Environment* _internal_add_enviorment();
  public:
  const ::aasdk::proto::data::Environment& enviorment(int index) const;
  ::aasdk::proto::data::Environment* add_enviorment();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Environment >&
      enviorment() const;

  // repeated .aasdk.proto.data.HVAC hvac = 12;
  int hvac_size() const;
  private:
  int _internal_hvac_size() const;
  public:
  void clear_hvac();
  ::aasdk::proto::data::HVAC* mutable_hvac(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::HVAC >*
      mutable_hvac();
  private:
  const ::aasdk::proto::data::HVAC& _internal_hvac(int index) const;
  ::aasdk::proto::data::HVAC* _internal_add_hvac();
  public:
  const ::aasdk::proto::data::HVAC& hvac(int index) const;
  ::aasdk::proto::data::HVAC* add_hvac();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::HVAC >&
      hvac() const;

  // repeated .aasdk.proto.data.DrivingStatus driving_status = 13;
  int driving_status_size() const;
  private:
  int _internal_driving_status_size() const;
  public:
  void clear_driving_status();
  ::aasdk::proto::data::DrivingStatus* mutable_driving_status(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::DrivingStatus >*
      mutable_driving_status();
  private:
  const ::aasdk::proto::data::DrivingStatus& _internal_driving_status(int index) const;
  ::aasdk::proto::data::DrivingStatus* _internal_add_driving_status();
  public:
  const ::aasdk::proto::data::DrivingStatus& driving_status(int index) const;
  ::aasdk::proto::data::DrivingStatus* add_driving_status();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::DrivingStatus >&
      driving_status() const;

  // repeated .aasdk.proto.data.SteeringWheel steering_wheel = 14;
  int steering_wheel_size() const;
  private:
  int _internal_steering_wheel_size() const;
  public:
  void clear_steering_wheel();
  ::aasdk::proto::data::SteeringWheel* mutable_steering_wheel(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::SteeringWheel >*
      mutable_steering_wheel();
  private:
  const ::aasdk::proto::data::SteeringWheel& _internal_steering_wheel(int index) const;
  ::aasdk::proto::data::SteeringWheel* _internal_add_steering_wheel();
  public:
  const ::aasdk::proto::data::SteeringWheel& steering_wheel(int index) const;
  ::aasdk::proto::data::SteeringWheel* add_steering_wheel();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::SteeringWheel >&
      steering_wheel() const;

  // repeated .aasdk.proto.data.Passenger passenger = 15;
  int passenger_size() const;
  private:
  int _internal_passenger_size() const;
  public:
  void clear_passenger();
  ::aasdk::proto::data::Passenger* mutable_passenger(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Passenger >*
      mutable_passenger();
  private:
  const ::aasdk::proto::data::Passenger& _internal_passenger(int index) const;
  ::aasdk::proto::data::Passenger* _internal_add_passenger();
  public:
  const ::aasdk::proto::data::Passenger& passenger(int index) const;
  ::aasdk::proto::data::Passenger* add_passenger();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Passenger >&
      passenger() const;

  // repeated .aasdk.proto.data.Door door = 16;
  int door_size() const;
  private:
  int _internal_door_size() const;
  public:
  void clear_door();
  ::aasdk::proto::data::Door* mutable_door(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Door >*
      mutable_door();
  private:
  const ::aasdk::proto::data::Door& _internal_door(int index) const;
  ::aasdk::proto::data::Door* _internal_add_door();
  public:
  const ::aasdk::proto::data::Door& door(int index) const;
  ::aasdk::proto::data::Door* add_door();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Door >&
      door() const;

  // repeated .aasdk.proto.data.Light light = 17;
  int light_size() const;
  private:
  int _internal_light_size() const;
  public:
  void clear_light();
  ::aasdk::proto::data::Light* mutable_light(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Light >*
      mutable_light();
  private:
  const ::aasdk::proto::data::Light& _internal_light(int index) const;
  ::aasdk::proto::data::Light* _internal_add_light();
  public:
  const ::aasdk::proto::data::Light& light(int index) const;
  ::aasdk::proto::data::Light* add_light();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Light >&
      light() const;

  // repeated .aasdk.proto.data.Accel accel = 19;
  int accel_size() const;
  private:
  int _internal_accel_size() const;
  public:
  void clear_accel();
  ::aasdk::proto::data::Accel* mutable_accel(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Accel >*
      mutable_accel();
  private:
  const ::aasdk::proto::data::Accel& _internal_accel(int index) const;
  ::aasdk::proto::data::Accel* _internal_add_accel();
  public:
  const ::aasdk::proto::data::Accel& accel(int index) const;
  ::aasdk::proto::data::Accel* add_accel();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Accel >&
      accel() const;

  // repeated .aasdk.proto.data.Gyro gyro = 20;
  int gyro_size() const;
  private:
  int _internal_gyro_size() const;
  public:
  void clear_gyro();
  ::aasdk::proto::data::Gyro* mutable_gyro(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gyro >*
      mutable_gyro();
  private:
  const ::aasdk::proto::data::Gyro& _internal_gyro(int index) const;
  ::aasdk::proto::data::Gyro* _internal_add_gyro();
  public:
  const ::aasdk::proto::data::Gyro& gyro(int index) const;
  ::aasdk::proto::data::Gyro* add_gyro();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gyro >&
      gyro() const;

  // @@protoc_insertion_point(class_scope:aasdk.proto.messages.SensorEventIndication)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::GPSLocation > gps_location_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Compass > compass_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Speed > speed_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::RPM > rpm_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Odometer > odometer_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::FuelLevel > fuel_level_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::ParkingBrake > parking_brake_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gear > gear_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Diagnostics > diagnostics_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::NightMode > night_mode_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Environment > enviorment_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::HVAC > hvac_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::DrivingStatus > driving_status_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::SteeringWheel > steering_wheel_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Passenger > passenger_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Door > door_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Light > light_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Accel > accel_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gyro > gyro_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SensorEventIndicationMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SensorEventIndication

// repeated .aasdk.proto.data.GPSLocation gps_location = 1;
inline int SensorEventIndication::_internal_gps_location_size() const {
  return gps_location_.size();
}
inline int SensorEventIndication::gps_location_size() const {
  return _internal_gps_location_size();
}
inline ::aasdk::proto::data::GPSLocation* SensorEventIndication::mutable_gps_location(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.gps_location)
  return gps_location_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::GPSLocation >*
SensorEventIndication::mutable_gps_location() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.gps_location)
  return &gps_location_;
}
inline const ::aasdk::proto::data::GPSLocation& SensorEventIndication::_internal_gps_location(int index) const {
  return gps_location_.Get(index);
}
inline const ::aasdk::proto::data::GPSLocation& SensorEventIndication::gps_location(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.gps_location)
  return _internal_gps_location(index);
}
inline ::aasdk::proto::data::GPSLocation* SensorEventIndication::_internal_add_gps_location() {
  return gps_location_.Add();
}
inline ::aasdk::proto::data::GPSLocation* SensorEventIndication::add_gps_location() {
  ::aasdk::proto::data::GPSLocation* _add = _internal_add_gps_location();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.gps_location)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::GPSLocation >&
SensorEventIndication::gps_location() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.gps_location)
  return gps_location_;
}

// repeated .aasdk.proto.data.Compass compass = 2;
inline int SensorEventIndication::_internal_compass_size() const {
  return compass_.size();
}
inline int SensorEventIndication::compass_size() const {
  return _internal_compass_size();
}
inline ::aasdk::proto::data::Compass* SensorEventIndication::mutable_compass(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.compass)
  return compass_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Compass >*
SensorEventIndication::mutable_compass() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.compass)
  return &compass_;
}
inline const ::aasdk::proto::data::Compass& SensorEventIndication::_internal_compass(int index) const {
  return compass_.Get(index);
}
inline const ::aasdk::proto::data::Compass& SensorEventIndication::compass(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.compass)
  return _internal_compass(index);
}
inline ::aasdk::proto::data::Compass* SensorEventIndication::_internal_add_compass() {
  return compass_.Add();
}
inline ::aasdk::proto::data::Compass* SensorEventIndication::add_compass() {
  ::aasdk::proto::data::Compass* _add = _internal_add_compass();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.compass)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Compass >&
SensorEventIndication::compass() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.compass)
  return compass_;
}

// repeated .aasdk.proto.data.Speed speed = 3;
inline int SensorEventIndication::_internal_speed_size() const {
  return speed_.size();
}
inline int SensorEventIndication::speed_size() const {
  return _internal_speed_size();
}
inline ::aasdk::proto::data::Speed* SensorEventIndication::mutable_speed(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.speed)
  return speed_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Speed >*
SensorEventIndication::mutable_speed() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.speed)
  return &speed_;
}
inline const ::aasdk::proto::data::Speed& SensorEventIndication::_internal_speed(int index) const {
  return speed_.Get(index);
}
inline const ::aasdk::proto::data::Speed& SensorEventIndication::speed(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.speed)
  return _internal_speed(index);
}
inline ::aasdk::proto::data::Speed* SensorEventIndication::_internal_add_speed() {
  return speed_.Add();
}
inline ::aasdk::proto::data::Speed* SensorEventIndication::add_speed() {
  ::aasdk::proto::data::Speed* _add = _internal_add_speed();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.speed)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Speed >&
SensorEventIndication::speed() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.speed)
  return speed_;
}

// repeated .aasdk.proto.data.RPM rpm = 4;
inline int SensorEventIndication::_internal_rpm_size() const {
  return rpm_.size();
}
inline int SensorEventIndication::rpm_size() const {
  return _internal_rpm_size();
}
inline ::aasdk::proto::data::RPM* SensorEventIndication::mutable_rpm(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.rpm)
  return rpm_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::RPM >*
SensorEventIndication::mutable_rpm() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.rpm)
  return &rpm_;
}
inline const ::aasdk::proto::data::RPM& SensorEventIndication::_internal_rpm(int index) const {
  return rpm_.Get(index);
}
inline const ::aasdk::proto::data::RPM& SensorEventIndication::rpm(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.rpm)
  return _internal_rpm(index);
}
inline ::aasdk::proto::data::RPM* SensorEventIndication::_internal_add_rpm() {
  return rpm_.Add();
}
inline ::aasdk::proto::data::RPM* SensorEventIndication::add_rpm() {
  ::aasdk::proto::data::RPM* _add = _internal_add_rpm();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.rpm)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::RPM >&
SensorEventIndication::rpm() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.rpm)
  return rpm_;
}

// repeated .aasdk.proto.data.Odometer odometer = 5;
inline int SensorEventIndication::_internal_odometer_size() const {
  return odometer_.size();
}
inline int SensorEventIndication::odometer_size() const {
  return _internal_odometer_size();
}
inline ::aasdk::proto::data::Odometer* SensorEventIndication::mutable_odometer(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.odometer)
  return odometer_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Odometer >*
SensorEventIndication::mutable_odometer() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.odometer)
  return &odometer_;
}
inline const ::aasdk::proto::data::Odometer& SensorEventIndication::_internal_odometer(int index) const {
  return odometer_.Get(index);
}
inline const ::aasdk::proto::data::Odometer& SensorEventIndication::odometer(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.odometer)
  return _internal_odometer(index);
}
inline ::aasdk::proto::data::Odometer* SensorEventIndication::_internal_add_odometer() {
  return odometer_.Add();
}
inline ::aasdk::proto::data::Odometer* SensorEventIndication::add_odometer() {
  ::aasdk::proto::data::Odometer* _add = _internal_add_odometer();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.odometer)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Odometer >&
SensorEventIndication::odometer() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.odometer)
  return odometer_;
}

// repeated .aasdk.proto.data.FuelLevel fuel_level = 6;
inline int SensorEventIndication::_internal_fuel_level_size() const {
  return fuel_level_.size();
}
inline int SensorEventIndication::fuel_level_size() const {
  return _internal_fuel_level_size();
}
inline ::aasdk::proto::data::FuelLevel* SensorEventIndication::mutable_fuel_level(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.fuel_level)
  return fuel_level_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::FuelLevel >*
SensorEventIndication::mutable_fuel_level() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.fuel_level)
  return &fuel_level_;
}
inline const ::aasdk::proto::data::FuelLevel& SensorEventIndication::_internal_fuel_level(int index) const {
  return fuel_level_.Get(index);
}
inline const ::aasdk::proto::data::FuelLevel& SensorEventIndication::fuel_level(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.fuel_level)
  return _internal_fuel_level(index);
}
inline ::aasdk::proto::data::FuelLevel* SensorEventIndication::_internal_add_fuel_level() {
  return fuel_level_.Add();
}
inline ::aasdk::proto::data::FuelLevel* SensorEventIndication::add_fuel_level() {
  ::aasdk::proto::data::FuelLevel* _add = _internal_add_fuel_level();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.fuel_level)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::FuelLevel >&
SensorEventIndication::fuel_level() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.fuel_level)
  return fuel_level_;
}

// repeated .aasdk.proto.data.ParkingBrake parking_brake = 7;
inline int SensorEventIndication::_internal_parking_brake_size() const {
  return parking_brake_.size();
}
inline int SensorEventIndication::parking_brake_size() const {
  return _internal_parking_brake_size();
}
inline ::aasdk::proto::data::ParkingBrake* SensorEventIndication::mutable_parking_brake(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.parking_brake)
  return parking_brake_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::ParkingBrake >*
SensorEventIndication::mutable_parking_brake() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.parking_brake)
  return &parking_brake_;
}
inline const ::aasdk::proto::data::ParkingBrake& SensorEventIndication::_internal_parking_brake(int index) const {
  return parking_brake_.Get(index);
}
inline const ::aasdk::proto::data::ParkingBrake& SensorEventIndication::parking_brake(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.parking_brake)
  return _internal_parking_brake(index);
}
inline ::aasdk::proto::data::ParkingBrake* SensorEventIndication::_internal_add_parking_brake() {
  return parking_brake_.Add();
}
inline ::aasdk::proto::data::ParkingBrake* SensorEventIndication::add_parking_brake() {
  ::aasdk::proto::data::ParkingBrake* _add = _internal_add_parking_brake();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.parking_brake)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::ParkingBrake >&
SensorEventIndication::parking_brake() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.parking_brake)
  return parking_brake_;
}

// repeated .aasdk.proto.data.Gear gear = 8;
inline int SensorEventIndication::_internal_gear_size() const {
  return gear_.size();
}
inline int SensorEventIndication::gear_size() const {
  return _internal_gear_size();
}
inline ::aasdk::proto::data::Gear* SensorEventIndication::mutable_gear(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.gear)
  return gear_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gear >*
SensorEventIndication::mutable_gear() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.gear)
  return &gear_;
}
inline const ::aasdk::proto::data::Gear& SensorEventIndication::_internal_gear(int index) const {
  return gear_.Get(index);
}
inline const ::aasdk::proto::data::Gear& SensorEventIndication::gear(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.gear)
  return _internal_gear(index);
}
inline ::aasdk::proto::data::Gear* SensorEventIndication::_internal_add_gear() {
  return gear_.Add();
}
inline ::aasdk::proto::data::Gear* SensorEventIndication::add_gear() {
  ::aasdk::proto::data::Gear* _add = _internal_add_gear();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.gear)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gear >&
SensorEventIndication::gear() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.gear)
  return gear_;
}

// repeated .aasdk.proto.data.Diagnostics diagnostics = 9;
inline int SensorEventIndication::_internal_diagnostics_size() const {
  return diagnostics_.size();
}
inline int SensorEventIndication::diagnostics_size() const {
  return _internal_diagnostics_size();
}
inline ::aasdk::proto::data::Diagnostics* SensorEventIndication::mutable_diagnostics(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.diagnostics)
  return diagnostics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Diagnostics >*
SensorEventIndication::mutable_diagnostics() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.diagnostics)
  return &diagnostics_;
}
inline const ::aasdk::proto::data::Diagnostics& SensorEventIndication::_internal_diagnostics(int index) const {
  return diagnostics_.Get(index);
}
inline const ::aasdk::proto::data::Diagnostics& SensorEventIndication::diagnostics(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.diagnostics)
  return _internal_diagnostics(index);
}
inline ::aasdk::proto::data::Diagnostics* SensorEventIndication::_internal_add_diagnostics() {
  return diagnostics_.Add();
}
inline ::aasdk::proto::data::Diagnostics* SensorEventIndication::add_diagnostics() {
  ::aasdk::proto::data::Diagnostics* _add = _internal_add_diagnostics();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.diagnostics)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Diagnostics >&
SensorEventIndication::diagnostics() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.diagnostics)
  return diagnostics_;
}

// repeated .aasdk.proto.data.NightMode night_mode = 10;
inline int SensorEventIndication::_internal_night_mode_size() const {
  return night_mode_.size();
}
inline int SensorEventIndication::night_mode_size() const {
  return _internal_night_mode_size();
}
inline ::aasdk::proto::data::NightMode* SensorEventIndication::mutable_night_mode(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.night_mode)
  return night_mode_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::NightMode >*
SensorEventIndication::mutable_night_mode() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.night_mode)
  return &night_mode_;
}
inline const ::aasdk::proto::data::NightMode& SensorEventIndication::_internal_night_mode(int index) const {
  return night_mode_.Get(index);
}
inline const ::aasdk::proto::data::NightMode& SensorEventIndication::night_mode(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.night_mode)
  return _internal_night_mode(index);
}
inline ::aasdk::proto::data::NightMode* SensorEventIndication::_internal_add_night_mode() {
  return night_mode_.Add();
}
inline ::aasdk::proto::data::NightMode* SensorEventIndication::add_night_mode() {
  ::aasdk::proto::data::NightMode* _add = _internal_add_night_mode();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.night_mode)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::NightMode >&
SensorEventIndication::night_mode() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.night_mode)
  return night_mode_;
}

// repeated .aasdk.proto.data.Environment enviorment = 11;
inline int SensorEventIndication::_internal_enviorment_size() const {
  return enviorment_.size();
}
inline int SensorEventIndication::enviorment_size() const {
  return _internal_enviorment_size();
}
inline ::aasdk::proto::data::Environment* SensorEventIndication::mutable_enviorment(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.enviorment)
  return enviorment_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Environment >*
SensorEventIndication::mutable_enviorment() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.enviorment)
  return &enviorment_;
}
inline const ::aasdk::proto::data::Environment& SensorEventIndication::_internal_enviorment(int index) const {
  return enviorment_.Get(index);
}
inline const ::aasdk::proto::data::Environment& SensorEventIndication::enviorment(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.enviorment)
  return _internal_enviorment(index);
}
inline ::aasdk::proto::data::Environment* SensorEventIndication::_internal_add_enviorment() {
  return enviorment_.Add();
}
inline ::aasdk::proto::data::Environment* SensorEventIndication::add_enviorment() {
  ::aasdk::proto::data::Environment* _add = _internal_add_enviorment();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.enviorment)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Environment >&
SensorEventIndication::enviorment() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.enviorment)
  return enviorment_;
}

// repeated .aasdk.proto.data.HVAC hvac = 12;
inline int SensorEventIndication::_internal_hvac_size() const {
  return hvac_.size();
}
inline int SensorEventIndication::hvac_size() const {
  return _internal_hvac_size();
}
inline ::aasdk::proto::data::HVAC* SensorEventIndication::mutable_hvac(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.hvac)
  return hvac_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::HVAC >*
SensorEventIndication::mutable_hvac() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.hvac)
  return &hvac_;
}
inline const ::aasdk::proto::data::HVAC& SensorEventIndication::_internal_hvac(int index) const {
  return hvac_.Get(index);
}
inline const ::aasdk::proto::data::HVAC& SensorEventIndication::hvac(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.hvac)
  return _internal_hvac(index);
}
inline ::aasdk::proto::data::HVAC* SensorEventIndication::_internal_add_hvac() {
  return hvac_.Add();
}
inline ::aasdk::proto::data::HVAC* SensorEventIndication::add_hvac() {
  ::aasdk::proto::data::HVAC* _add = _internal_add_hvac();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.hvac)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::HVAC >&
SensorEventIndication::hvac() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.hvac)
  return hvac_;
}

// repeated .aasdk.proto.data.DrivingStatus driving_status = 13;
inline int SensorEventIndication::_internal_driving_status_size() const {
  return driving_status_.size();
}
inline int SensorEventIndication::driving_status_size() const {
  return _internal_driving_status_size();
}
inline ::aasdk::proto::data::DrivingStatus* SensorEventIndication::mutable_driving_status(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.driving_status)
  return driving_status_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::DrivingStatus >*
SensorEventIndication::mutable_driving_status() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.driving_status)
  return &driving_status_;
}
inline const ::aasdk::proto::data::DrivingStatus& SensorEventIndication::_internal_driving_status(int index) const {
  return driving_status_.Get(index);
}
inline const ::aasdk::proto::data::DrivingStatus& SensorEventIndication::driving_status(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.driving_status)
  return _internal_driving_status(index);
}
inline ::aasdk::proto::data::DrivingStatus* SensorEventIndication::_internal_add_driving_status() {
  return driving_status_.Add();
}
inline ::aasdk::proto::data::DrivingStatus* SensorEventIndication::add_driving_status() {
  ::aasdk::proto::data::DrivingStatus* _add = _internal_add_driving_status();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.driving_status)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::DrivingStatus >&
SensorEventIndication::driving_status() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.driving_status)
  return driving_status_;
}

// repeated .aasdk.proto.data.SteeringWheel steering_wheel = 14;
inline int SensorEventIndication::_internal_steering_wheel_size() const {
  return steering_wheel_.size();
}
inline int SensorEventIndication::steering_wheel_size() const {
  return _internal_steering_wheel_size();
}
inline ::aasdk::proto::data::SteeringWheel* SensorEventIndication::mutable_steering_wheel(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.steering_wheel)
  return steering_wheel_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::SteeringWheel >*
SensorEventIndication::mutable_steering_wheel() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.steering_wheel)
  return &steering_wheel_;
}
inline const ::aasdk::proto::data::SteeringWheel& SensorEventIndication::_internal_steering_wheel(int index) const {
  return steering_wheel_.Get(index);
}
inline const ::aasdk::proto::data::SteeringWheel& SensorEventIndication::steering_wheel(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.steering_wheel)
  return _internal_steering_wheel(index);
}
inline ::aasdk::proto::data::SteeringWheel* SensorEventIndication::_internal_add_steering_wheel() {
  return steering_wheel_.Add();
}
inline ::aasdk::proto::data::SteeringWheel* SensorEventIndication::add_steering_wheel() {
  ::aasdk::proto::data::SteeringWheel* _add = _internal_add_steering_wheel();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.steering_wheel)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::SteeringWheel >&
SensorEventIndication::steering_wheel() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.steering_wheel)
  return steering_wheel_;
}

// repeated .aasdk.proto.data.Passenger passenger = 15;
inline int SensorEventIndication::_internal_passenger_size() const {
  return passenger_.size();
}
inline int SensorEventIndication::passenger_size() const {
  return _internal_passenger_size();
}
inline ::aasdk::proto::data::Passenger* SensorEventIndication::mutable_passenger(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.passenger)
  return passenger_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Passenger >*
SensorEventIndication::mutable_passenger() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.passenger)
  return &passenger_;
}
inline const ::aasdk::proto::data::Passenger& SensorEventIndication::_internal_passenger(int index) const {
  return passenger_.Get(index);
}
inline const ::aasdk::proto::data::Passenger& SensorEventIndication::passenger(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.passenger)
  return _internal_passenger(index);
}
inline ::aasdk::proto::data::Passenger* SensorEventIndication::_internal_add_passenger() {
  return passenger_.Add();
}
inline ::aasdk::proto::data::Passenger* SensorEventIndication::add_passenger() {
  ::aasdk::proto::data::Passenger* _add = _internal_add_passenger();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.passenger)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Passenger >&
SensorEventIndication::passenger() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.passenger)
  return passenger_;
}

// repeated .aasdk.proto.data.Door door = 16;
inline int SensorEventIndication::_internal_door_size() const {
  return door_.size();
}
inline int SensorEventIndication::door_size() const {
  return _internal_door_size();
}
inline ::aasdk::proto::data::Door* SensorEventIndication::mutable_door(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.door)
  return door_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Door >*
SensorEventIndication::mutable_door() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.door)
  return &door_;
}
inline const ::aasdk::proto::data::Door& SensorEventIndication::_internal_door(int index) const {
  return door_.Get(index);
}
inline const ::aasdk::proto::data::Door& SensorEventIndication::door(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.door)
  return _internal_door(index);
}
inline ::aasdk::proto::data::Door* SensorEventIndication::_internal_add_door() {
  return door_.Add();
}
inline ::aasdk::proto::data::Door* SensorEventIndication::add_door() {
  ::aasdk::proto::data::Door* _add = _internal_add_door();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.door)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Door >&
SensorEventIndication::door() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.door)
  return door_;
}

// repeated .aasdk.proto.data.Light light = 17;
inline int SensorEventIndication::_internal_light_size() const {
  return light_.size();
}
inline int SensorEventIndication::light_size() const {
  return _internal_light_size();
}
inline ::aasdk::proto::data::Light* SensorEventIndication::mutable_light(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.light)
  return light_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Light >*
SensorEventIndication::mutable_light() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.light)
  return &light_;
}
inline const ::aasdk::proto::data::Light& SensorEventIndication::_internal_light(int index) const {
  return light_.Get(index);
}
inline const ::aasdk::proto::data::Light& SensorEventIndication::light(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.light)
  return _internal_light(index);
}
inline ::aasdk::proto::data::Light* SensorEventIndication::_internal_add_light() {
  return light_.Add();
}
inline ::aasdk::proto::data::Light* SensorEventIndication::add_light() {
  ::aasdk::proto::data::Light* _add = _internal_add_light();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.light)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Light >&
SensorEventIndication::light() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.light)
  return light_;
}

// repeated .aasdk.proto.data.Accel accel = 19;
inline int SensorEventIndication::_internal_accel_size() const {
  return accel_.size();
}
inline int SensorEventIndication::accel_size() const {
  return _internal_accel_size();
}
inline ::aasdk::proto::data::Accel* SensorEventIndication::mutable_accel(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.accel)
  return accel_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Accel >*
SensorEventIndication::mutable_accel() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.accel)
  return &accel_;
}
inline const ::aasdk::proto::data::Accel& SensorEventIndication::_internal_accel(int index) const {
  return accel_.Get(index);
}
inline const ::aasdk::proto::data::Accel& SensorEventIndication::accel(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.accel)
  return _internal_accel(index);
}
inline ::aasdk::proto::data::Accel* SensorEventIndication::_internal_add_accel() {
  return accel_.Add();
}
inline ::aasdk::proto::data::Accel* SensorEventIndication::add_accel() {
  ::aasdk::proto::data::Accel* _add = _internal_add_accel();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.accel)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Accel >&
SensorEventIndication::accel() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.accel)
  return accel_;
}

// repeated .aasdk.proto.data.Gyro gyro = 20;
inline int SensorEventIndication::_internal_gyro_size() const {
  return gyro_.size();
}
inline int SensorEventIndication::gyro_size() const {
  return _internal_gyro_size();
}
inline ::aasdk::proto::data::Gyro* SensorEventIndication::mutable_gyro(int index) {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.messages.SensorEventIndication.gyro)
  return gyro_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gyro >*
SensorEventIndication::mutable_gyro() {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.messages.SensorEventIndication.gyro)
  return &gyro_;
}
inline const ::aasdk::proto::data::Gyro& SensorEventIndication::_internal_gyro(int index) const {
  return gyro_.Get(index);
}
inline const ::aasdk::proto::data::Gyro& SensorEventIndication::gyro(int index) const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.SensorEventIndication.gyro)
  return _internal_gyro(index);
}
inline ::aasdk::proto::data::Gyro* SensorEventIndication::_internal_add_gyro() {
  return gyro_.Add();
}
inline ::aasdk::proto::data::Gyro* SensorEventIndication::add_gyro() {
  ::aasdk::proto::data::Gyro* _add = _internal_add_gyro();
  // @@protoc_insertion_point(field_add:aasdk.proto.messages.SensorEventIndication.gyro)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aasdk::proto::data::Gyro >&
SensorEventIndication::gyro() const {
  // @@protoc_insertion_point(field_list:aasdk.proto.messages.SensorEventIndication.gyro)
  return gyro_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace proto
}  // namespace aasdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SensorEventIndicationMessage_2eproto
