LOCAL_PATH:= $(call my-dir)

LIBUSB_PATH := $(LOCAL_PATH)
include $(CLEAR_VARS)
LOCAL_MODULE := libusb-1.0
LOCAL_SRC_FILES := $(LIBUSB_PATH)/lib/$(TARGET_ARCH_ABI)/libusb1.0.a
LOCAL_EXPORT_C_INCLUDES := $(LIBUSB_PATH)/include
include $(PREBUILT_STATIC_LIBRARY)
